### ISSUE TITLE
Mixed Content Error

### ISSUE THREAD

**Issue by Vihtal** [codibez/streetlabel#12]
hey i changed the positioning of the hud to the bottom near left of my map, but everytime i restart my server i gotta refresh it to move it back from top left and it gives me this error
https://cdn.discordapp.com/attachments/232182328821022720/870455788446036038/unknown.png

**Comment by Vihtal** [comment]
![](https://cdn.discordapp.com/attachments/232182328821022720/870466403814240297/unknown.png)

**Comment by finlayrough** [comment]
To fix it, go to resources/streetlabel/html/font-face.css and remove the top line. I might fork this to fix the problem for everyone.

**Comment by codibez** [comment]
This issue has been resolved with update 1.1.3
