### ISSUE TITLE
Question, not issue (works perfectly)

### ISSUE THREAD

**Issue by blakjak08** [codibez/streetlabel#9]
Is it possible to make the street names smaller? Where they aren't taking up as much room near the map?

**Comment by codibez** [comment]
#10 The previous version of street Label could accomplish this although the update **v1.1.0** just published will make the job a whole lot easier, enjoy.

**Comment by codibez** [comment]
#10 The previous version of street Label could accomplish this although the update **v1.1.0** just published will make the job a whole lot easier, enjoy.
